title: ItalianProgrammer Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.italianprogrammer.pizza
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC â€” Jan 2
  down: "#e60000"
  systems:
    - category: Websites
      name: Main Website
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: /img/icon_whip.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs: []
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: false
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Websites
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
